spring:
  datasource:
    url: jdbc:h2:mem:orchestratordb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop

  kafka:
    bootstrap-servers: localhost:9093

kafka:
  enabled: true

retry:
  scheduler:
    auto-enabled: false
stuck:
  detector:
    auto-enabled: false
